---
title: "AmesHousingPrices"
author: "DerekRogers"
date: "2022-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(naniar)
library(tidyverse)
library(ggplot2)
```

```{r}
#AmesHouesingDataFrame = data.frame(read.csv("C:/SMU MS Data Science/StatisticalFoundations6371/AmesHousePricing/train.csv"))

#AmesHouesingDataFrame <- read.csv("C:/Users/Joey/Desktop/stat project/AmesHousePricing/train.csv")
#plot_missing(AmesHouesingDataFrame[,1-15])

```

```{r}
# Many of these fields use Na purposefully to indicate that feature doesn't exist for that house according to the data descriptions
  # but others say nothing in the data description about Na values 

miss_var_summary(AmesHouesingDataFrame)
```

```{r}
AmesHouesingDataFrame$LogSalePrice = log(AmesHouesingDataFrame$SalePrice)

# Add 1 to all deck/porch square footage so a log transformation works (log(1) = 0)
AmesHouesingDataFrame$WoodDeckSF = AmesHouesingDataFrame$WoodDeckSF + 1
AmesHouesingDataFrame$OpenPorchSF = AmesHouesingDataFrame$OpenPorchSF + 1
AmesHouesingDataFrame$X3SsnPorch = AmesHouesingDataFrame$X3SsnPorch + 1
AmesHouesingDataFrame$ScreenPorch = AmesHouesingDataFrame$ScreenPorch + 1

# Create log transformation column for the various porch square foot columns
AmesHouesingDataFrame$LogWoodDeckSF = log(AmesHouesingDataFrame$WoodDeckSF)
AmesHouesingDataFrame$LogOpenPorchSF = log(AmesHouesingDataFrame$OpenPorchSF)
AmesHouesingDataFrame$LogX3SsnPorch = log(AmesHouesingDataFrame$X3SsnPorch)
AmesHouesingDataFrame$LogScreenPorch = log(AmesHouesingDataFrame$ScreenPorch)

AmesHouesingDataFrame
```


```{r}
apply(AmesHouesingDataFrame, 2, function(x) length(unique(x)))
ncol(AmesHouesingDataFrame)
```

<<<<<<< HEAD

The data contain many NA values. These NA values are not necessarily missing data, but can be thought of as
a missing feature of certain homes. 
```{r}
AmesHouesingDataFrame$Fence <- as.character(AmesHouesingDataFrame$Fence)
AmesHouesingDataFrame$Fence[is.na(AmesHouesingDataFrame$Fence)] <- "None"
AmesHouesingDataFrame$Fence <- as.factor(AmesHouesingDataFrame$Fence)

# MSZoning: Identifies the general zoning classification of the sale.
AmesHouesingDataFrame$MSZoning <- as.character(AmesHouesingDataFrame$MSZoning)
AmesHouesingDataFrame$MSZoning[is.na(AmesHouesingDataFrame$MSZoning)] <- "None"
AmesHouesingDataFrame$MSZoning <- as.factor(AmesHouesingDataFrame$MSZoning)

# Exterior1st: Exterior covering on house
AmesHouesingDataFrame$Exterior1st <- as.character(AmesHouesingDataFrame$Exterior1st)
AmesHouesingDataFrame$Exterior1st[is.na(AmesHouesingDataFrame$Exterior1st)] <- "None"
AmesHouesingDataFrame$Exterior1st <- as.factor(AmesHouesingDataFrame$Exterior1st)

#Exterior2nd: Exterior covering on house (if more than one material)
AmesHouesingDataFrame$Exterior2nd <- as.character(AmesHouesingDataFrame$Exterior2nd)
AmesHouesingDataFrame$Exterior2nd[is.na(AmesHouesingDataFrame$Exterior2nd)] <- "None"
AmesHouesingDataFrame$Exterior2nd <- as.factor(AmesHouesingDataFrame$Exterior2nd)

AmesHouesingDataFrame$GarageType <- as.character(AmesHouesingDataFrame$GarageType)
AmesHouesingDataFrame$GarageType[is.na(AmesHouesingDataFrame$GarageType)] <- "None"
AmesHouesingDataFrame$GarageType <- as.factor(AmesHouesingDataFrame$GarageType)
                                              
AmesHouesingDataFrame$FireplaceQu <- as.character(AmesHouesingDataFrame$FireplaceQu)
AmesHouesingDataFrame$FireplaceQu[is.na(AmesHouesingDataFrame$FireplaceQu)] <- "None"
AmesHouesingDataFrame$FireplaceQu <- as.factor(AmesHouesingDataFrame$FireplaceQu)

AmesHouesingDataFrame$Alley <- as.character(AmesHouesingDataFrame$Alley)
AmesHouesingDataFrame$Alley[is.na(AmesHouesingDataFrame$Alley)] <- "None"
AmesHouesingDataFrame$Alley <- as.factor(AmesHouesingDataFrame$Alley)

AmesHouesingDataFrame$BsmtQual <- as.character(AmesHouesingDataFrame$BsmtQual)
AmesHouesingDataFrame$BsmtQual[is.na(AmesHouesingDataFrame$BsmtQual)] <- "None"
AmesHouesingDataFrame$BsmtQual <- as.factor(AmesHouesingDataFrame$BsmtQual)

AmesHouesingDataFrame$BsmtCond <- as.character(AmesHouesingDataFrame$BsmtCond)
AmesHouesingDataFrame$BsmtCond[is.na(AmesHouesingDataFrame$BsmtCond)] <- "None"
AmesHouesingDataFrame$BsmtCond <- as.factor(AmesHouesingDataFrame$BsmtCond)

AmesHouesingDataFrame$BsmtExposure <- as.character(AmesHouesingDataFrame$BsmtExposure)
AmesHouesingDataFrame$BsmtExposure[is.na(AmesHouesingDataFrame$BsmtExposure)] <- "None"
AmesHouesingDataFrame$BsmtExposure <- as.factor(AmesHouesingDataFrame$BsmtExposure)

AmesHouesingDataFrame$BsmtFinType1 <- as.character(AmesHouesingDataFrame$BsmtFinType1)
AmesHouesingDataFrame$BsmtFinType1[is.na(AmesHouesingDataFrame$BsmtFinType1)] <- "None"
AmesHouesingDataFrame$BsmtFinType1 <- as.factor(AmesHouesingDataFrame$BsmtFinType1)

AmesHouesingDataFrame$BsmtFinType2 <- as.character(AmesHouesingDataFrame$BsmtFinType2)
AmesHouesingDataFrame$BsmtFinType2[is.na(AmesHouesingDataFrame$BsmtFinType2)] <- "None"
AmesHouesingDataFrame$BsmtFinType2<- as.factor(AmesHouesingDataFrame$BsmtFinType2)

AmesHouesingDataFrame$GarageFinish <- as.character(AmesHouesingDataFrame$GarageFinish)
AmesHouesingDataFrame$GarageFinish[is.na(AmesHouesingDataFrame$GarageFinish)] <- "None"
AmesHouesingDataFrame$GarageFinish <- as.factor(AmesHouesingDataFrame$GarageFinish)

AmesHouesingDataFrame$GarageQual <- as.character(AmesHouesingDataFrame$GarageQual)
AmesHouesingDataFrame$GarageQual[is.na(AmesHouesingDataFrame$GarageQual)] <- "None"
AmesHouesingDataFrame$GarageQual <- as.factor(AmesHouesingDataFrame$GarageQual)

AmesHouesingDataFrame$GarageCond <- as.character(AmesHouesingDataFrame$GarageCond)
AmesHouesingDataFrame$GarageCond[is.na(AmesHouesingDataFrame$GarageCond)] <- "None"
AmesHouesingDataFrame$GarageCond <- as.factor(AmesHouesingDataFrame$GarageCond)

#MiscFeature: Miscellaneous feature not covered in other categories
AmesHouesingDataFrame$MiscFeature <- as.character(AmesHouesingDataFrame$MiscFeature)
AmesHouesingDataFrame$MiscFeature[is.na(AmesHouesingDataFrame$MiscFeature)] <- "None"
AmesHouesingDataFrame$MiscFeature <- as.factor(AmesHouesingDataFrame$MiscFeature)                               

# MasVnrType: Masonry veneer type
AmesHouesingDataFrame$MasVnrType <- as.character(AmesHouesingDataFrame$MasVnrType)
AmesHouesingDataFrame$MasVnrType[is.na(AmesHouesingDataFrame$MasVnrType)] <- "None"
AmesHouesingDataFrame$MasVnrType <- as.factor(AmesHouesingDataFrame$MasVnrType)
```
                                              
```{r}
# Histogram that shows a right skewed normal distribution
hist(AmesHouesingDataFrame$SalePrice, xlab='House Price (dollars)', main='Histogram of Housing Prices')

# Box plot that shows a right skew
boxplot(AmesHouesingDataFrame$SalePrice, xlab = "Houses", ylab = "House Price (dollars)", main = "Boxplot of Housing Prices")

# QQ plot where the prices drift away from the identity line
qqnorm(AmesHouesingDataFrame$SalePrice, pch = 1, frame = FALSE, main = "Q-Q Plot For Housing Prices", ylab = "House Price (dollars)")
qqline(AmesHouesingDataFrame$SalePrice, col = "steelblue", lwd = 2)
```

```{r}
# A log transformation of housing prices reduces the right skewness of the histogram and boxplot as well as keeps housing prices closer to the identity line in the QQ plot

# Histogram
hist(AmesHouesingDataFrame$LogSalePrice, xlab='House Price in log(dollars)', main='Histogram of Log Housing Prices')

# Box plot
boxplot(AmesHouesingDataFrame$LogSalePrice, xlab = "Houses", ylab = "House Price in log(dollars)", main = "Boxplot of Log Housing Prices")

# QQ plot
qqnorm(AmesHouesingDataFrame$LogSalePrice, pch = 1, frame = FALSE, main = "Q-Q Plot for Log Housing Prices", ylab = "House Price in log(dollars)")
qqline(AmesHouesingDataFrame$LogSalePrice, col = "steelblue", lwd = 2)
```

```{r}
# There are 2 extreme outliers for 2Story houses that are way below the prediction interval at the middle right of the graph
AmesHouesingDataFrame %>% ggplot(aes(x = GrLivArea, y = LogSalePrice, color = HouseStyle)) + 
  geom_jitter() + geom_smooth(method = "lm") +
  labs(title="Above ground living area vs log(sales price) in Ames Iowa")
```

```{r}
fit = lm(LogSalePrice~GrLivArea, data = AmesHouesingDataFrame)
summary(fit)
```

```{r}

```

```{r}

```