---
title: "project 2"
author: "Joey Hernandez"
date: "2022-12-02"
output: html_document
---

```{r setup, include=FALSE}
library(gbm)
library(mice)
library(moments)
library(ggplot2)
library(tidyverse)
library(janitor)
library(readxl)
library(GGally)
library(ggplot2)
library(treemapify)
library(gridExtra)
library(grid)
library(scales)
library(ggcorrplot)
library(corrplot)
library(class)
library(caret)
library(pROC)
library(e1071)
library(kableExtra)
library(StepReg)
library(ggthemes)
library(olsrr)
library(stargazer)
library(car)
library(leaps)
library(forecast)

AmesHouesingDataFrame <- read.csv("C:/Users/Joey/Desktop/stat project/AmesHousePricing/train.csv", header = TRUE)

AmesHouesingDataFrame_test <- read.csv("C:/Users/Joey/Desktop/house-prices-advanced-regression-techniques/test.csv",header = TRUE)

```




```{r}
AmesHouesingDataFrame$LogSalePrice = log(AmesHouesingDataFrame$SalePrice)

AmesHouesingDataFrame$LogX1stFlrSF = log(AmesHouesingDataFrame$X1stFlrSF + 1)
AmesHouesingDataFrame$LogX2ndFlrSF = log(AmesHouesingDataFrame$X2ndFlrSF + 1)
AmesHouesingDataFrame$LogGrLivArea = log(AmesHouesingDataFrame$GrLivArea + 1)

AmesHouesingDataFrame$LogTotalBsmtSF = log(AmesHouesingDataFrame$TotalBsmtSF + 1)
AmesHouesingDataFrame$LogBsmtUnfSF = log(AmesHouesingDataFrame$BsmtUnfSF + 1)

AmesHouesingDataFrame$LogWoodDeckSF = log(AmesHouesingDataFrame$WoodDeckSF + 1)
AmesHouesingDataFrame$LogOpenPorchSF = log(AmesHouesingDataFrame$OpenPorchSF + 1)
AmesHouesingDataFrame$LogX3SsnPorch = log(AmesHouesingDataFrame$X3SsnPorch + 1)
AmesHouesingDataFrame$LogScreenPorch = log(AmesHouesingDataFrame$ScreenPorch + 1)

AmesHouesingDataFrame$LogLotArea = log(AmesHouesingDataFrame$LotArea + 1)
AmesHouesingDataFrame$LogLotFrontage = log(AmesHouesingDataFrame$LotFrontage + 1)

AmesHouesingDataFrame$LogPoolArea = log(AmesHouesingDataFrame$PoolArea + 1)

AmesHouesingDataFrame$LogGarageArea = log(AmesHouesingDataFrame$GarageArea + 1)

AmesHouesingDataFrame$LogMasVnrArea = log(AmesHouesingDataFrame$MasVnrArea + 1)

AmesHouesingDataFrame = AmesHouesingDataFrame[!(AmesHouesingDataFrame$Id == "524" | AmesHouesingDataFrame$Id == "1299"),]
dim(AmesHouesingDataFrame)




# w/o messing around too much with transforms etc. I want to get 
# baseline vars together that may have an impact on prices of homes. 
home_vars <- c('Id','MSZoning','Utilities', 'Neighborhood','BldgType','HouseStyle',
                'OverallQual','OverallCond','YearBuilt', 'ExterQual','ExterCond',
                'BsmtQual','BsmtCond','TotalBsmtSF','Heating','HeatingQC', 
                'CentralAir','Electrical','BedroomAbvGr','KitchenAbvGr',
                'KitchenQual','TotRmsAbvGrd','Functional','Fireplaces','FireplaceQu',
               'GarageArea','GarageQual','GarageCond','OpenPorchSF',#'PoolArea',,'GrLivArea'"LogX1stFlrSF", "LogX2ndFlrSF","LogPoolArea",
                'Fence','MoSold','YrSold','SaleType','SaleCondition','SalePrice',
                "LogGrLivArea","LogTotalBsmtSF",
               "LogWoodDeckSF","LogOpenPorchSF","LogX3SsnPorch","LogScreenPorch",
               "LogLotArea","LogLotFrontage","LogGarageArea","LogMasVnrArea"
               )

# creating the training set
home_train_vars <- AmesHouesingDataFrame[,home_vars]

# we do know that sales price needs to be logged... so at least let's get that
# in here...
home_train_vars$lSalePrice <- log(home_train_vars$SalePrice)

# some factors/vars need to be updated for use in our model/interpertations etc. 
home_train_vars$ExterCond2 <- as.numeric(factor(home_train_vars$ExterCond,
                                                levels = c("Ex","Gd","TA","Fa","Po"),
                                                labels = c(5,4,3,2,1), ordered = TRUE))

home_train_vars$HeatingQC2 <- as.numeric(factor(home_train_vars$HeatingQC, 
                                  levels = c("Ex", "Gd","TA", "Fa","Po"),
                                  labels = c(5,4,3,2,1) ,ordered = TRUE))

home_train_vars$CentralAir2 <- as.numeric(factor(home_train_vars$CentralAir, 
                                  levels = c("N", "Y"),
                                  labels = c(0,1) ,ordered = TRUE))



```



```{r}
# Filtering for 3 key neighborhoods
three_n <- AmesHouesingDataFrame %>%
  filter(Neighborhood == "NAmes" | Neighborhood == "Edwards" | Neighborhood == "BrkSide")

# how is sales price related to square footage? 
# Squarefootage = GrLIvArea 
# is the relationship between SalesPrice and SquareFootage 
# dependent on the neighborhood? 


three_n %>% 
  ggplot(aes(log(GrLivArea), log(SalePrice), color= as.factor(MSSubClass))) +
  geom_point() + ggtitle("Saleprice v GrLivArea | MSSubClass")

three_n %>% 
  ggplot(aes(log(GrLivArea), log(SalePrice), color= LotShape)) +
  geom_point(size = 3, alpha = .7) + ggtitle("Log Sale Price  v. Log Live Area | LotShape") +
  ylab("Log Sale Price")+ xlab("Log Ground Living Area")

# plot for Year sold and LOG sale price. price seems to be down in 2008 (which is when the outlier was sold)
AmesHouesingDataFrame %>%
  ggplot(aes(log(SalePrice), as.factor(YrSold), fill = as.factor(YrSold)))+
  geom_boxplot(color = "black") + coord_flip() +
  ggtitle("Log Sale Price: 2006-2010") + xlab("Log Sale Price") +
  ylab("Year")

three_n  %>% 
  ggplot(aes(log(GrLivArea), log(SalePrice), color = as.factor(SaleCondition))) +
  geom_point(size = 2) + ggtitle("Sale Price v. GrLivArea | Sale Condition")


```

First Model
```{r}

# bringing in some of the feats for trial in model...
# still using basic stuff. 
model_var <- c('SalePrice', 
                'OverallQual','OverallCond','YearBuilt','ExterCond2',
                'TotalBsmtSF','HeatingQC2', 
                'CentralAir2','BedroomAbvGr','KitchenAbvGr',
                'TotRmsAbvGrd','Fireplaces',
                'GarageArea','OpenPorchSF',#'PoolArea','GrLivArea', "LogX1stFlrSF", "LogX2ndFlrSF""LogPoolArea",
                 'YrSold', "LogGrLivArea","LogTotalBsmtSF",
               "LogWoodDeckSF","LogOpenPorchSF","LogX3SsnPorch","LogScreenPorch",
               "LogLotArea","LogLotFrontage","LogGarageArea","LogMasVnrArea"
               )


lr_model <- home_train_vars[,model_var]
lr_model$lSalePrice <- log(lr_model$SalePrice)

set.seed(4)
train.index <- sample(c(1:dim(lr_model)[1]), dim(lr_model)[1]*0.8)
lr_model_train <- lr_model[train.index,]
lr_model_test <- lr_model[-train.index,]

home_regression <- lm(lSalePrice~.-SalePrice, data = lr_model_train)
summary(home_regression)

# note "response" this will give you numerical result min/1stq /median/mean/3rd q/ max/ NA's
pred1 <- predict(home_regression, lr_model_test, type = "response")
# summary(pred1)

residuals <- lr_model_test$lSalePrice - pred1

home_regression_pred <- data.frame("Predicted" = pred1, "Actual" = lr_model_test$lSalePrice, "Residual" = residuals)

# returns ME-RMSE-MAE-MPE-MAPE
accuracy(pred1, lr_model_test$lSalePrice)


# note "predict" this returns fit/lwr/upr
pred2 <- predict(home_regression, interval = "predict", newdata = lr_model_test) 
# summary(pred2)

stargazer(home_regression, type = 'text')

car::vif(home_regression)
 #comment out so we don't hang up the console with time
ols_step_both_p(home_regression, prem = .05, details = FALSE)
```



Second Model 
```{r}
# adjusted vars to use in model after above:

adj_var <- c("OverallQual", "LogGrLivArea","YearBuilt","LogLotArea",
             "OverallCond","TotalBsmtSF","LogGarageArea","Fireplaces",
             "HeatingQC2","KitchenAbvGr","LogScreenPorch","BedroomAbvGr",
             "LogWoodDeckSF", "SalePrice")


lr_model2 <- home_train_vars[,adj_var]
lr_model2$lSalePrice <- log(lr_model2$SalePrice)

set.seed(4)
train.index <- sample(c(1:dim(lr_model2)[1]), dim(lr_model2)[1]*0.8)
lr_model_train2 <- lr_model2[train.index,]
lr_model_test2 <- lr_model2[-train.index,]

home_reg2 <- lm(lSalePrice ~ . -SalePrice, data = lr_model_train2)



pred3 <- predict(home_reg2,lr_model_test2,type = "response")

residuals2 <- lr_model_test2$lSalePrice - pred3

home_reg_pred2 <- data.frame("Predicted" = pred3, "Actual" = lr_model_test2$lSalePrice, "Residual" = residuals2)

# returns ME-RMSE-MAE-MPE-MAPE
accuracy(pred3, lr_model_test2$lSalePrice)

pred4 <- predict(home_reg2, interval = "predict", newdata = lr_model_test2)

RMSE <- sqrt(mean((pred4[,1] - lr_model_test2$lSalePrice)^2))
RMSE

stargazer(home_reg2, type = 'text')

car::vif(home_reg2)

```

```{r}
hdata <- read.csv("C:/Users/Joey/Desktop/house-prices-advanced-regression-techniques/test.csv",header = TRUE)



hdata$LogX1stFlrSF = log(hdata$X1stFlrSF + 1)
hdata$LogX2ndFlrSF = log(hdata$X2ndFlrSF + 1)
hdata$LogGrLivArea = log(hdata$GrLivArea + 1)

hdata$LogTotalBsmtSF = log(hdata$TotalBsmtSF + 1)
hdata$LogBsmtUnfSF = log(hdata$BsmtUnfSF + 1)

hdata$LogWoodDeckSF = log(hdata$WoodDeckSF + 1)
hdata$LogOpenPorchSF = log(hdata$OpenPorchSF + 1)
hdata$LogX3SsnPorch = log(hdata$X3SsnPorch + 1)
hdata$LogScreenPorch = log(hdata$ScreenPorch + 1)

hdata$LogLotArea = log(hdata$LotArea + 1)
hdata$LogLotFrontage = log(hdata$LotFrontage + 1)

hdata$LogPoolArea = log(hdata$PoolArea + 1)

hdata$LogGarageArea = log(hdata$GarageArea + 1)

hdata$LogMasVnrArea = log(hdata$MasVnrArea + 1)

hdata$ExterCond2 <- as.numeric(factor(hdata$ExterCond,
                                                levels = c("Ex","Gd","TA","Fa","Po"),
                                                labels = c(5,4,3,2,1), ordered = TRUE))

hdata$HeatingQC2 <- as.numeric(factor(hdata$HeatingQC, 
                                  levels = c("Ex", "Gd","TA", "Fa","Po"),
                                  labels = c(5,4,3,2,1) ,ordered = TRUE))

hdata$CentralAir2 <- as.numeric(factor(hdata$CentralAir, 
                                  levels = c("N", "Y"),
                                  labels = c(0,1) ,ordered = TRUE))


hfit <- lm(lSalePrice ~ .-SalePrice, data = lr_model)

hdata$SalePrice = as.numeric(NA)
hpred <- predict(hfit, interval = "predict", newdata = hdata)

h_prediction <- data.frame(cbind(hdata$Id, hpred[,1]))

names(h_prediction) <- c("ID", "MonthlyIncome")


write.csv(h_prediction, file = "./housePred.csv", row.names = FALSE)

```
