---
title: "PorchEDA"
author: "DerekRogers"
date: "2022-11-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(naniar)
library(ggplot2)
library(dplyr)
```

```{r}
# Feature engineer an overall porch value from the columns:
#    WoodDeckSF - requires log transformation
#    OpenPorchSF - requires log transformation
#    EnclosedPorch - DOES NOT require log transformation
#    X3SsnPorch - requires log transformation but doesn't have a significant p value
#    ScreenPorch - requires log transformation
```

```{r}
AmesHouesingDataFrame = data.frame(read.csv("C:/SMU MS Data Science/StatisticalFoundations6371/AmesHousePricing/train.csv"))
AmesHouesingDataFrame$LogSalePrice = log(AmesHouesingDataFrame$SalePrice)

# Create log transformation column for the various porch square foot columns
AmesHouesingDataFrame$LogWoodDeckSF = log(AmesHouesingDataFrame$WoodDeckSF + 1)
AmesHouesingDataFrame$LogOpenPorchSF = log(AmesHouesingDataFrame$OpenPorchSF + 1)
AmesHouesingDataFrame$LogEnclosedPorch = log(AmesHouesingDataFrame$EnclosedPorch + 1)
AmesHouesingDataFrame$LogX3SsnPorch = log(AmesHouesingDataFrame$X3SsnPorch + 1)
AmesHouesingDataFrame$LogScreenPorch = log(AmesHouesingDataFrame$ScreenPorch + 1)

AmesHouesingDataFrame
```

```{r}
#Shows a right skew for WoodDeckSF that is corrected with a log transformation

AmesHouesingDataFrameWoodDeck = filter(AmesHouesingDataFrame, WoodDeckSF > 1)

# Histogram
hist(AmesHouesingDataFrameWoodDeck$WoodDeckSF, xlab='Wood Deck Size in feet^2', main='Histogram of Wood Deck Size')

# Box plot
boxplot(AmesHouesingDataFrameWoodDeck$WoodDeckSF, xlab = "Wood Deck", ylab = "Wood Deck Size in feet^2", main = "Boxplot of Wood Deck Size")

# QQ plot
qqnorm(AmesHouesingDataFrameWoodDeck$WoodDeckSF, pch = 1, frame = FALSE, main = "Q-Q Plot for Wood Deck Size", ylab = "Wood Deck Size in feet^2")
qqline(AmesHouesingDataFrameWoodDeck$WoodDeckSF, col = "steelblue", lwd = 2)

# Histogram
hist(AmesHouesingDataFrameWoodDeck$LogWoodDeckSF, xlab='Wood Deck Size in log(feet^2)', main='Histogram of Log Wood Deck Size')

# Box plot
boxplot(AmesHouesingDataFrameWoodDeck$LogWoodDeckSF, xlab = "Wood Deck", ylab = "Wood Deck Size in log(feet^2)", main = "Boxplot of Log Wood Deck Size")

# QQ plot
qqnorm(AmesHouesingDataFrameWoodDeck$LogWoodDeckSF, pch = 1, frame = FALSE, main = "Q-Q Plot for Log Wood Deck Size", ylab = "Wood Deck Size in log(feet^2)")
qqline(AmesHouesingDataFrameWoodDeck$LogWoodDeckSF, col = "steelblue", lwd = 2)

AmesHouesingDataFrameWoodDeck %>% ggplot(aes(x = LogWoodDeckSF, y = LogSalePrice, color = HouseStyle)) + 
  geom_jitter() + geom_smooth(method = "lm") +
  labs(title="log(Wood Deck Size) vs log(sales price) in Ames Iowa")

fit = lm(LogSalePrice~LogWoodDeckSF, data = AmesHouesingDataFrameWoodDeck)
summary(fit)
```

```{r}
#Shows a right skew for OpenPorchSF that is corrected with a log transformation

AmesHouesingDataFrameOpenPorch = filter(AmesHouesingDataFrame, OpenPorchSF > 1)

# Histogram
hist(AmesHouesingDataFrameOpenPorch$OpenPorchSF, xlab='Open Porch Size in feet^2', main='Histogram of Open Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameOpenPorch$OpenPorchSF, xlab = "Open Porch", ylab = "Open Porch Size in feet^2", main = "Boxplot of Open Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameOpenPorch$OpenPorchSF, pch = 1, frame = FALSE, main = "Q-Q Plot for Open Porch Size", ylab = "Open Porch Size in feet^2")
qqline(AmesHouesingDataFrameOpenPorch$OpenPorchSF, col = "steelblue", lwd = 2)

# Histogram
hist(AmesHouesingDataFrameOpenPorch$LogOpenPorchSF, xlab='Open Porch Size in log(feet^2)', main='Histogram of Log Open Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameOpenPorch$LogOpenPorchSF, xlab = "Open Porch", ylab = "Open Porch Size in log(feet^2)", main = "Boxplot of Log Open Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameOpenPorch$LogOpenPorchSF, pch = 1, frame = FALSE, main = "Q-Q Plot for Log Open Porch Size", ylab = "Open Porch Size in log(feet^2)")
qqline(AmesHouesingDataFrameOpenPorch$LogOpenPorchSF, col = "steelblue", lwd = 2)

AmesHouesingDataFrameOpenPorch %>% ggplot(aes(x = LogOpenPorchSF, y = LogSalePrice, color = HouseStyle)) + 
  geom_jitter() + geom_smooth(method = "lm") +
  labs(title="log(Open Porch Size) vs log(sales price) in Ames Iowa")

fit = lm(LogSalePrice~LogOpenPorchSF, data = AmesHouesingDataFrameOpenPorch)
summary(fit)
```

```{r}
#Shows a right skew for EnclosedPorch but a log transformation doesn't seem to help

AmesHouesingDataFrameEnclosedPorch = filter(AmesHouesingDataFrame, EnclosedPorch > 1)

# Histogram
hist(AmesHouesingDataFrameEnclosedPorch$EnclosedPorch, xlab='Enclosed Porch Size in feet^2', main='Histogram of Enclosed Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameEnclosedPorch$EnclosedPorch, xlab = "Enclosed Porch", ylab = "Enclosed Porch Size in feet^2", main = "Boxplot of Enclosed Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameEnclosedPorch$EnclosedPorch, pch = 1, frame = FALSE, main = "Q-Q Plot for Enclosed Porch Size", ylab = "Enclosed Porch Size in feet^2")
qqline(AmesHouesingDataFrameEnclosedPorch$EnclosedPorch, col = "steelblue", lwd = 2)

# Histogram
hist(AmesHouesingDataFrameEnclosedPorch$LogEnclosedPorch, xlab='Enclosed Porch Size in log(feet^2)', main='Histogram of Log Enclosed Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameEnclosedPorch$LogEnclosedPorch, xlab = "Enclosed Porch", ylab = "Enclosed Porch Size in log(feet^2)", main = "Boxplot of Log Enclosed Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameEnclosedPorch$LogEnclosedPorch, pch = 1, frame = FALSE, main = "Q-Q Plot for Log Enclosed Porch Size", ylab = "Enclosed Porch Size in log(feet^2)")
qqline(AmesHouesingDataFrameEnclosedPorch$LogEnclosedPorch, col = "steelblue", lwd = 2)

AmesHouesingDataFrameEnclosedPorch %>% ggplot(aes(x = EnclosedPorch, y = LogSalePrice, color = HouseStyle)) + 
  geom_jitter() + geom_smooth(method = "lm") +
  labs(title="Enclosed Porch Size (feet squared) vs log(sales price) in Ames Iowa")

fit = lm(LogSalePrice~EnclosedPorch, data = AmesHouesingDataFrameEnclosedPorch)
summary(fit)
```

```{r}
#Shows a right skew for X3SsnPorch that is corrected with a log transformation

AmesHouesingDataFrameX3SsnPorch = filter(AmesHouesingDataFrame, X3SsnPorch > 1)

# Histogram
hist(AmesHouesingDataFrameX3SsnPorch$X3SsnPorch, xlab='Three Season Porch Size in feet^2', main='Histogram of Three Season Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameX3SsnPorch$X3SsnPorch, xlab = "Three Season Porch", ylab = "Three Season Porch Size in feet^2", main = "Boxplot of Three Season Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameX3SsnPorch$X3SsnPorch, pch = 1, frame = FALSE, main = "Q-Q Plot for Three Season Porch Size", ylab = "Three Season Porch Size in feet^2")
qqline(AmesHouesingDataFrameX3SsnPorch$X3SsnPorch, col = "steelblue", lwd = 2)

# Histogram
hist(AmesHouesingDataFrameX3SsnPorch$LogX3SsnPorch, xlab='Three Season Porch Size in log(feet^2)', main='Histogram of Log Three Season Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameX3SsnPorch$LogX3SsnPorch, xlab = "Three Season Porch", ylab = "Three Season Porch Size in log(feet^2)", main = "Boxplot of Log Three Season Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameX3SsnPorch$LogX3SsnPorch, pch = 1, frame = FALSE, main = "Q-Q Plot for Log Three Season Porch Size", ylab = "Three Season Porch Size in log(feet^2)")
qqline(AmesHouesingDataFrameX3SsnPorch$LogX3SsnPorch, col = "steelblue", lwd = 2)

AmesHouesingDataFrameX3SsnPorch %>% ggplot(aes(x = LogX3SsnPorch, y = LogSalePrice, color = HouseStyle)) + 
  geom_jitter() + geom_smooth(method = "lm") +
  labs(title="log(Three Season Porch Size) vs log(sales price) in Ames Iowa")

fit = lm(LogSalePrice~LogX3SsnPorch, data = AmesHouesingDataFrameX3SsnPorch)
summary(fit)
```

```{r}
#Shows a right skew for ScreenPorch that is corrected with a log transformation

AmesHouesingDataFrameScreenPorch = filter(AmesHouesingDataFrame, ScreenPorch > 1)

# Histogram
hist(AmesHouesingDataFrameScreenPorch$ScreenPorch, xlab='Screen Porch Size in feet^2', main='Histogram of Screen Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameScreenPorch$ScreenPorch, xlab = "Screen Porch", ylab = "Screen Porch Size in feet^2", main = "Boxplot of Screen Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameScreenPorch$ScreenPorch, pch = 1, frame = FALSE, main = "Q-Q Plot for Screen Porch Size", ylab = "Screen Porch Size in feet^2")
qqline(AmesHouesingDataFrameScreenPorch$ScreenPorch, col = "steelblue", lwd = 2)

# Histogram
hist(AmesHouesingDataFrameScreenPorch$LogScreenPorch, xlab='Screen Porch Size in log(feet^2)', main='Histogram of Log Screen Porch Size')

# Box plot
boxplot(AmesHouesingDataFrameScreenPorch$LogScreenPorch, xlab = "Screen Porch", ylab = "Screen Porch Size in log(feet^2)", main = "Boxplot of Log Screen Porch Size")

# QQ plot
qqnorm(AmesHouesingDataFrameScreenPorch$LogScreenPorch, pch = 1, frame = FALSE, main = "Q-Q Plot for Log Screen Porch Size", ylab = "Screen Porch Size in log(feet^2)")
qqline(AmesHouesingDataFrameScreenPorch$LogScreenPorch, col = "steelblue", lwd = 2)

AmesHouesingDataFrameScreenPorch %>% ggplot(aes(x = LogScreenPorch, y = LogSalePrice, color = HouseStyle)) + 
  geom_jitter() + geom_smooth(method = "lm") +
  labs(title="log(Screen Porch Size) vs log(sales price) in Ames Iowa")

fit = lm(LogSalePrice~LogScreenPorch, data = AmesHouesingDataFrameScreenPorch)
summary(fit)
```

```{r}
# Todo: need to figure out how to combine these models.Each is using a dataframe that only contains rows with non zero values675

fit = lm(LogSalePrice~LogWoodDeckSF, data = AmesHouesingDataFrameWoodDeck)
summary(fit)

fit = lm(LogSalePrice~LogOpenPorchSF, data = AmesHouesingDataFrameOpenPorch)
summary(fit)

fit = lm(LogSalePrice~EnclosedPorch, data = AmesHouesingDataFrameEnclosedPorch)
summary(fit)

fit = lm(LogSalePrice~LogScreenPorch, data = AmesHouesingDataFrameScreenPorch)
summary(fit)
```

```{r}

```
