---
title: "HousingPricesModelTemplate"
author: "Derek Rogers"
date: "2022-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(naniar)
library(tidyverse)
library(ggplot2)
library(plyr)
library(ggcorrplot)
library(gridExtra)
library(olsrr)
library(gbm)
library(mice)
library(moments)
library(janitor)
library(readxl)
library(GGally)
library(treemapify)
library(grid)
library(scales)
library(corrplot)
library(class)
library(caret)
library(pROC)
library(e1071)
library(kableExtra)
library(StepReg)
library(ggthemes)
library(stargazer)
library(car)
library(leaps)
library(epiR)
library(forecast)
library(ggplot2)
library(mosaic)
library(dplyr)
library(GGally)
library(gtools)
library(ggfortify)
library(readr)
library(dplyr)
library(ggpubr)
library(modelr)
library(corrplot)
library(caret)
library(mlbench)
library(scales)
library(olsrr)
library(tidyverse)
library(RColorBrewer)
library(tidyverse)
library(ggplot2)
library(scales)
library(pwr)
library(agricolae)
library(huxtable)
library(lawstat)
library(lsmeans)
library(nCDunnett)
library(dplyr)
library(WDI)
library(investr)
library(multcomp)
library(pairwiseCI)
library(DescTools)
library(GGally)
library(olsrr)
library(lmtest)

```

```{r}
#AmesHouesingDataFrame = data.frame(read.csv("C:/SMU MS Data Science/StatisticalFoundations6371/AmesHousePricing/train.csv"))
#AmesHouesingTestDataFrame = data.frame(read.csv("C:/SMU MS Data Science/StatisticalFoundations6371/AmesHousePricing/test.csv"))

AmesHouesingDataFrame <- read.csv("C:/Users/Joey/Desktop/stat project/AmesHousePricing/train.csv")
AmesHouesingDataFrame_test<-read.csv("C:/Users/Joey/Desktop/house-prices-advanced-regression-techniques/test.csv")

#AmesHouesingDataFrame <- read.csv("C:/Users/nicol/OneDrive/Desktop/train1.csv")
#AmesHouesingDataFrame <- read.csv("C:/Users/nicol/OneDrive/Desktop/test1.csv")
```

```{r}
# Perform log transformations on columns that require it which was determined from the various *EDA.Rmd files and listed in Notes.txt

AmesHouesingDataFrame$LogSalePrice = log(AmesHouesingDataFrame$SalePrice)

AmesHouesingDataFrame$LogX1stFlrSF = log(AmesHouesingDataFrame$X1stFlrSF + 1)
AmesHouesingDataFrame$LogX2ndFlrSF = log(AmesHouesingDataFrame$X2ndFlrSF + 1)
AmesHouesingDataFrame$LogGrLivArea = log(AmesHouesingDataFrame$GrLivArea + 1)

AmesHouesingDataFrame$LogTotalBsmtSF = log(AmesHouesingDataFrame$TotalBsmtSF + 1)
AmesHouesingDataFrame$LogBsmtUnfSF = log(AmesHouesingDataFrame$BsmtUnfSF + 1)

AmesHouesingDataFrame$LogWoodDeckSF = log(AmesHouesingDataFrame$WoodDeckSF + 1)
AmesHouesingDataFrame$LogOpenPorchSF = log(AmesHouesingDataFrame$OpenPorchSF + 1)
AmesHouesingDataFrame$LogX3SsnPorch = log(AmesHouesingDataFrame$X3SsnPorch + 1)
AmesHouesingDataFrame$LogScreenPorch = log(AmesHouesingDataFrame$ScreenPorch + 1)

AmesHouesingDataFrame$LogLotArea = log(AmesHouesingDataFrame$LotArea + 1)
AmesHouesingDataFrame$LogLotFrontage = log(AmesHouesingDataFrame$LotFrontage + 1)

AmesHouesingDataFrame$LogPoolArea = log(AmesHouesingDataFrame$PoolArea + 1)

AmesHouesingDataFrame$LogGarageArea = log(AmesHouesingDataFrame$GarageArea + 1)

AmesHouesingDataFrame$LogMasVnrArea = log(AmesHouesingDataFrame$MasVnrArea + 1)
```

```{r}
# The data contain many NA values. These NA values are not necessarily missing data, but can be thought of as
# a missing feature of certain homes.

AmesHouesingDataFrame$Fence <- as.character(AmesHouesingDataFrame$Fence)
AmesHouesingDataFrame$Fence[is.na(AmesHouesingDataFrame$Fence)] <- "None"
AmesHouesingDataFrame$Fence <- as.factor(AmesHouesingDataFrame$Fence)

# MSZoning: Identifies the general zoning classification of the sale.
AmesHouesingDataFrame$MSZoning <- as.character(AmesHouesingDataFrame$MSZoning)
AmesHouesingDataFrame$MSZoning[is.na(AmesHouesingDataFrame$MSZoning)] <- "None"
AmesHouesingDataFrame$MSZoning <- as.factor(AmesHouesingDataFrame$MSZoning)

# Exterior1st: Exterior covering on house
AmesHouesingDataFrame$Exterior1st <- as.character(AmesHouesingDataFrame$Exterior1st)
AmesHouesingDataFrame$Exterior1st[is.na(AmesHouesingDataFrame$Exterior1st)] <- "None"
AmesHouesingDataFrame$Exterior1st <- as.factor(AmesHouesingDataFrame$Exterior1st)

#Exterior2nd: Exterior covering on house (if more than one material)
AmesHouesingDataFrame$Exterior2nd <- as.character(AmesHouesingDataFrame$Exterior2nd)
AmesHouesingDataFrame$Exterior2nd[is.na(AmesHouesingDataFrame$Exterior2nd)] <- "None"
AmesHouesingDataFrame$Exterior2nd <- as.factor(AmesHouesingDataFrame$Exterior2nd)

AmesHouesingDataFrame$GarageType <- as.character(AmesHouesingDataFrame$GarageType)
AmesHouesingDataFrame$GarageType[is.na(AmesHouesingDataFrame$GarageType)] <- "None"
AmesHouesingDataFrame$GarageType <- as.factor(AmesHouesingDataFrame$GarageType)
                                              
AmesHouesingDataFrame$FireplaceQu <- as.character(AmesHouesingDataFrame$FireplaceQu)
AmesHouesingDataFrame$FireplaceQu[is.na(AmesHouesingDataFrame$FireplaceQu)] <- "None"
AmesHouesingDataFrame$FireplaceQu <- as.factor(AmesHouesingDataFrame$FireplaceQu)

AmesHouesingDataFrame$Alley <- as.character(AmesHouesingDataFrame$Alley)
AmesHouesingDataFrame$Alley[is.na(AmesHouesingDataFrame$Alley)] <- "None"
AmesHouesingDataFrame$Alley <- as.factor(AmesHouesingDataFrame$Alley)

AmesHouesingDataFrame$BsmtQual <- as.character(AmesHouesingDataFrame$BsmtQual)
AmesHouesingDataFrame$BsmtQual[is.na(AmesHouesingDataFrame$BsmtQual)] <- "None"
AmesHouesingDataFrame$BsmtQual <- as.factor(AmesHouesingDataFrame$BsmtQual)

AmesHouesingDataFrame$BsmtCond <- as.character(AmesHouesingDataFrame$BsmtCond)
AmesHouesingDataFrame$BsmtCond[is.na(AmesHouesingDataFrame$BsmtCond)] <- "None"
AmesHouesingDataFrame$BsmtCond <- as.factor(AmesHouesingDataFrame$BsmtCond)

AmesHouesingDataFrame$BsmtExposure <- as.character(AmesHouesingDataFrame$BsmtExposure)
AmesHouesingDataFrame$BsmtExposure[is.na(AmesHouesingDataFrame$BsmtExposure)] <- "None"
AmesHouesingDataFrame$BsmtExposure <- as.factor(AmesHouesingDataFrame$BsmtExposure)

AmesHouesingDataFrame$BsmtFinType1 <- as.character(AmesHouesingDataFrame$BsmtFinType1)
AmesHouesingDataFrame$BsmtFinType1[is.na(AmesHouesingDataFrame$BsmtFinType1)] <- "None"
AmesHouesingDataFrame$BsmtFinType1 <- as.factor(AmesHouesingDataFrame$BsmtFinType1)

AmesHouesingDataFrame$BsmtFinType2 <- as.character(AmesHouesingDataFrame$BsmtFinType2)
AmesHouesingDataFrame$BsmtFinType2[is.na(AmesHouesingDataFrame$BsmtFinType2)] <- "None"
AmesHouesingDataFrame$BsmtFinType2<- as.factor(AmesHouesingDataFrame$BsmtFinType2)

AmesHouesingDataFrame$GarageFinish <- as.character(AmesHouesingDataFrame$GarageFinish)
AmesHouesingDataFrame$GarageFinish[is.na(AmesHouesingDataFrame$GarageFinish)] <- "None"
AmesHouesingDataFrame$GarageFinish <- as.factor(AmesHouesingDataFrame$GarageFinish)

AmesHouesingDataFrame$GarageQual <- as.character(AmesHouesingDataFrame$GarageQual)
AmesHouesingDataFrame$GarageQual[is.na(AmesHouesingDataFrame$GarageQual)] <- "None"
AmesHouesingDataFrame$GarageQual <- as.factor(AmesHouesingDataFrame$GarageQual)

AmesHouesingDataFrame$GarageCond <- as.character(AmesHouesingDataFrame$GarageCond)
AmesHouesingDataFrame$GarageCond[is.na(AmesHouesingDataFrame$GarageCond)] <- "None"
AmesHouesingDataFrame$GarageCond <- as.factor(AmesHouesingDataFrame$GarageCond)

#MiscFeature: Miscellaneous feature not covered in other categories
AmesHouesingDataFrame$MiscFeature <- as.character(AmesHouesingDataFrame$MiscFeature)
AmesHouesingDataFrame$MiscFeature[is.na(AmesHouesingDataFrame$MiscFeature)] <- "None"
AmesHouesingDataFrame$MiscFeature <- as.factor(AmesHouesingDataFrame$MiscFeature)                               

# MasVnrType: Masonry veneer type
AmesHouesingDataFrame$MasVnrType <- as.character(AmesHouesingDataFrame$MasVnrType)
AmesHouesingDataFrame$MasVnrType[is.na(AmesHouesingDataFrame$MasVnrType)] <- "None"
AmesHouesingDataFrame$MasVnrType <- as.factor(AmesHouesingDataFrame$MasVnrType)
```

```{r}
# Numerical Encoding so that we can explore correlation:

AmesHouesingDataFrame$ExterCondNum <- as.numeric(factor(AmesHouesingDataFrame$ExterCond,
                                                        levels = c("Ex", "Fa", "Gd", "TA", "Po"),
                                                        labels = c(5,2,4,3,1), ordered = TRUE))
AmesHouesingDataFrame$HeatingQCNum <- as.numeric(factor(AmesHouesingDataFrame$HeatingQC,
                                                        levels = c("Ex", "Fa", "Gd", "TA", "Po"),
                                                        labels = c(5,2,4,3,1), ordered = TRUE))
AmesHouesingDataFrame$CentralAirNum <- as.numeric(factor(AmesHouesingDataFrame$CentralAir,
                                                         levels = c("N", "Y"),
                                                         labels = c(0,1), ordered = TRUE))
```

```{r}
# Numerical Encoding so that we can explore correlation for LOT VAR

AmesHouesingDataFrame$LotShapeNum <- as.numeric(factor(AmesHouesingDataFrame$LotShape,
                                                        levels = c("Reg", "IR1", "IR2", "IR3"),
                                                        labels = c(4,3,2,1), ordered = TRUE))

AmesHouesingDataFrame$LandContourNum <- as.numeric(factor(AmesHouesingDataFrame$LandContour,
                                                        levels = c("Lvl", "Bnk", "HLS", "Low"),
                                                        labels = c(4,3,2,1), ordered = TRUE))

AmesHouesingDataFrame$LotConfigNum <- as.numeric(factor(AmesHouesingDataFrame$LotConfig,
                                                         levels = c("Inside",
                                                                    "Corner",
                                                                    "CulDSac","FR2",
                                                                    "FR3"),
                                                         labels = c(5,4,3,2,1), ordered = TRUE))

AmesHouesingDataFrame$LandSlopeNum <- as.numeric(factor(AmesHouesingDataFrame$LandSlope,
                                                     levels = c("Gtl", "Mod", "Sev"),
                                                     labels = c(3,2,1),
                                                     ordered = TRUE))
```

```{r}
# Removed outliers

AmesHouesingDataFrame
Outliers = AmesHouesingDataFrame[order(-AmesHouesingDataFrame$GrLivArea),]
Outliers = Outliers[1:2,]
Outliers
AmesHouesingDataFrame = AmesHouesingDataFrame[!(AmesHouesingDataFrame$Id=="524" | AmesHouesingDataFrame$Id=="1299"),]
AmesHouesingDataFrame
```

```{r}
# Final Features in Cyclone model
model_var = c('LogSalePrice','OverallQual','OverallCond','YearBuilt',
              'ExterCondNum','LogTotalBsmtSF','HeatingQCNum', 
              'BedroomAbvGr','Fireplaces', 'LogGarageArea', 
              "LogGrLivArea","LogWoodDeckSF","LogScreenPorch","LogLotArea")

# initial list of variables to consider
  # c('LogSalePrice','OverallQual','OverallCond','YearBuilt',
  #             'ExterCondNum','LogTotalBsmtSF','HeatingQCNum',
  #             'CentralAirNum','BedroomAbvGr','KitchenAbvGr',
  #             'TotRmsAbvGrd','Fireplaces', 'LogGarageArea',
  #             'LogOpenPorchSF','YrSold', "LogGrLivArea","LogWoodDeckSF",
  #             "LogScreenPorch","LogLotArea","LogMasVnrArea")


```

```{r}
hdata <- read.csv("C:/Users/Joey/Desktop/house-prices-advanced-regression-techniques/test.csv",header = TRUE)
#hdata <- read.csv("C:/SMU MS Data Science/StatisticalFoundations6371/AmesHousePricing/test.csv",header = TRUE)

# The data contain many NA values. These NA values are not necessarily missing data, but can be thought of as
# a missing feature of certain homes.

hdata$Fence <- as.character(hdata$Fence)
hdata$Fence[is.na(hdata$Fence)] <- "None"
hdata$Fence <- as.factor(hdata$Fence)

# MSZoning: Identifies the general zoning classification of the sale.
hdata$MSZoning <- as.character(hdata$MSZoning)
hdata$MSZoning[is.na(hdata$MSZoning)] <- "None"
hdata$MSZoning <- as.factor(hdata$MSZoning)

# Exterior1st: Exterior covering on house
hdata$Exterior1st <- as.character(hdata$Exterior1st)
hdata$Exterior1st[is.na(hdata$Exterior1st)] <- "None"
hdata$Exterior1st <- as.factor(hdata$Exterior1st)

#Exterior2nd: Exterior covering on house (if more than one material)
hdata$Exterior2nd <- as.character(hdata$Exterior2nd)
hdata$Exterior2nd[is.na(hdata$Exterior2nd)] <- "None"
hdata$Exterior2nd <- as.factor(hdata$Exterior2nd)

hdata$GarageType <- as.character(hdata$GarageType)
hdata$GarageType[is.na(hdata$GarageType)] <- "None"
hdata$GarageType <- as.factor(hdata$GarageType)
                                              
hdata$FireplaceQu <- as.character(hdata$FireplaceQu)
hdata$FireplaceQu[is.na(hdata$FireplaceQu)] <- "None"
hdata$FireplaceQu <- as.factor(hdata$FireplaceQu)

hdata$Alley <- as.character(hdata$Alley)
hdata$Alley[is.na(hdata$Alley)] <- "None"
hdata$Alley <- as.factor(hdata$Alley)

# hdata$BsmtQual <- as.character(AmesHouesingDataFrame$BsmtQual)
# hdata$BsmtQual[is.na(hdata$BsmtQual)] <- "None"
# hdata$BsmtQual <- as.factor(hdata$BsmtQual)

hdata$BsmtCond <- as.character(hdata$BsmtCond)
hdata$BsmtCond[is.na(hdata$BsmtCond)] <- "None"
hdata$BsmtCond <- as.factor(hdata$BsmtCond)

hdata$BsmtExposure <- as.character(hdata$BsmtExposure)
hdata$BsmtExposure[is.na(hdata$BsmtExposure)] <- "None"
hdata$BsmtExposure <- as.factor(hdata$BsmtExposure)

hdata$BsmtFinType1 <- as.character(hdata$BsmtFinType1)
hdata$BsmtFinType1[is.na(hdata$BsmtFinType1)] <- "None"
hdata$BsmtFinType1 <- as.factor(hdata$BsmtFinType1)

hdata$BsmtFinType2 <- as.character(hdata$BsmtFinType2)
hdata$BsmtFinType2[is.na(hdata$BsmtFinType2)] <- "None"
hdata$BsmtFinType2<- as.factor(hdata$BsmtFinType2)

hdata$GarageFinish <- as.character(hdata$GarageFinish)
hdata$GarageFinish[is.na(hdata$GarageFinish)] <- "None"
hdata$GarageFinish <- as.factor(hdata$GarageFinish)

hdata$GarageQual <- as.character(hdata$GarageQual)
hdata$GarageQual[is.na(hdata$GarageQual)] <- "None"
hdata$GarageQual <- as.factor(hdata$GarageQual)

hdata$GarageCond <- as.character(hdata$GarageCond)
hdata$GarageCond[is.na(hdata$GarageCond)] <- "None"
hdata$GarageCond <- as.factor(hdata$GarageCond)

#MiscFeature: Miscellaneous feature not covered in other categories
hdata$MiscFeature <- as.character(hdata$MiscFeature)
hdata$MiscFeature[is.na(hdata$MiscFeature)] <- "None"
hdata$MiscFeature <- as.factor(hdata$MiscFeature)                               

# MasVnrType: Masonry veneer type
hdata$MasVnrType <- as.character(hdata$MasVnrType)
hdata$MasVnrType[is.na(hdata$MasVnrType)] <- "None"
hdata$MasVnrType <- as.factor(hdata$MasVnrType)

hdata$LogX1stFlrSF = log(hdata$X1stFlrSF + 1)
hdata$LogX2ndFlrSF = log(hdata$X2ndFlrSF + 1)
hdata$LogGrLivArea = log(hdata$GrLivArea + 1)

hdata$LogTotalBsmtSF = log(hdata$TotalBsmtSF + 1)
hdata$LogBsmtUnfSF = log(hdata$BsmtUnfSF + 1)

hdata$LogWoodDeckSF = log(hdata$WoodDeckSF + 1)
hdata$LogOpenPorchSF = log(hdata$OpenPorchSF + 1)
hdata$LogX3SsnPorch = log(hdata$X3SsnPorch + 1)
hdata$LogScreenPorch = log(hdata$ScreenPorch + 1)

hdata$LogLotArea = log(hdata$LotArea + 1)
hdata$LogLotFrontage = log(hdata$LotFrontage + 1)

hdata$LogPoolArea = log(hdata$PoolArea + 1)

hdata$LogGarageArea = log(hdata$GarageArea + 1)

hdata$LogMasVnrArea = log(hdata$MasVnrArea + 1)

hdata$ExterCondNum <- as.numeric(factor(hdata$ExterCond,
                                                levels = c("Ex","Gd","TA","Fa","Po"),
                                                labels = c(5,4,3,2,1), ordered = TRUE))

hdata$HeatingQCNum <- as.numeric(factor(hdata$HeatingQC, 
                                  levels = c("Ex", "Gd","TA", "Fa","Po"),
                                  labels = c(5,4,3,2,1) ,ordered = TRUE))

hdata$CentralAirNum <- as.numeric(factor(hdata$CentralAir, 
                                  levels = c("N", "Y"),
                                  labels = c(0,1) ,ordered = TRUE))
```